# Generated by Django 2.0.6 on 2019-02-28 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewCar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('m0del', models.CharField(max_length=100)),
                ('year', models.IntegerField(default=2019)),
                ('mpg', models.IntegerField(default=0)),
            ],
        ),
    ]
